# Wind Statistics

### Introduction:

The data have been modified to contain some missing values, identified by NaN.  
Using pandas should make this exercise
easier, in particular for the bonus question.

You should be able to perform all of these operations without using
a for loop or other looping construct.


1. The data in 'wind.data' has the following format:

In [434]:
"""
Yr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL
61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04
61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83
61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71
"""

'\nYr Mo Dy   RPT   VAL   ROS   KIL   SHA   BIR   DUB   CLA   MUL   CLO   BEL   MAL\n61  1  1 15.04 14.96 13.17  9.29   NaN  9.87 13.67 10.25 10.83 12.58 18.50 15.04\n61  1  2 14.71   NaN 10.83  6.50 12.62  7.67 11.50 10.04  9.79  9.67 17.54 13.83\n61  1  3 18.50 16.88 12.33 10.13 11.17  6.17 11.25   NaN  8.50  7.67 12.75 12.71\n'

   The first three columns are year, month and day.  The
   remaining 12 columns are average windspeeds in knots at 12
   locations in Ireland on that day.   

   More information about the dataset go [here](wind.desc).

### Step 1. Import the necessary libraries

In [57]:
import pandas as pd
from datetime import timedelta

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data)

### Step 3. Assign it to a variable called data and replace the first 3 columns by a proper datetime index.

In [58]:
data=pd.read_csv("https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/06_Stats/Wind_Stats/wind.data",sep="\s+")
data['Date'] = data[['Yr', 'Mo','Dy']].astype(str).apply(lambda x: '-'.join(x), axis=1)
data.Date=pd.to_datetime(data.Date)
data=data.drop(['Dy', 'Mo', 'Yr'], axis = 1)
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Date
0,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,2061-01-01
1,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,2061-01-02
2,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,2061-01-03
3,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,2061-01-04
4,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,2061-01-05

### Step 4. Year 2061? Do we really have data from this year? Create a function to fix it and apply it.

In [59]:
data.loc[data.Date>pd.datetime.now(), "Date"] -= timedelta(days = 365.25 * 100)
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL,Date
0,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04,1961-01-01
1,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83,1961-01-02
2,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71,1961-01-03
3,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88,1961-01-04
4,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83,1961-01-05

### Step 5. Set the right dates as the index. Pay attention at the data type, it should be datetime64[ns].

In [60]:
data=data.set_index("Date")
data.head()

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
Date,,,,,,,,,,,,
1961-01-01,15.04,14.96,13.17,9.29,NaN,9.87,13.67,10.25,10.83,12.58,18.50,15.04
1961-01-02,14.71,NaN,10.83,6.50,12.62,7.67,11.50,10.04,9.79,9.67,17.54,13.83
1961-01-03,18.50,16.88,12.33,10.13,11.17,6.17,11.25,NaN,8.50,7.67,12.75,12.71
1961-01-04,10.58,6.63,11.75,4.58,4.54,2.88,8.63,1.79,5.83,5.88,5.46,10.88
1961-01-05,13.33,13.25,11.42,6.17,10.71,8.21,11.92,6.54,10.92,10.34,12.92,11.83

### Step 6. Compute how many values are missing for each location over the entire record.  
#### They should be ignored in all calculations below.

In [61]:
data.isnull().sum()

RPT    6
VAL    3
ROS    2
KIL    5
SHA    2
BIR    0
DUB    3
CLA    2
MUL    3
CLO    1
BEL    0
MAL    4
dtype: int64

### Step 7. Compute how many non-missing values there are in total.

In [62]:
data.notnull().sum().agg("sum")

78857

### Step 8. Calculate the mean windspeeds of the windspeeds over all the locations and all the times.
#### A single number for the entire dataset.

In [63]:
data.dropna(how="any",inplace=True)

In [64]:
data.shape

(6546, 12)

In [65]:
data.agg("sum").agg("sum")/(data.shape[0]*data.shape[1])

10.222465245951712

### Step 9. Create a DataFrame called loc_stats and calculate the min, max and mean windspeeds and standard deviations of the windspeeds at each location over all the days 

#### A different set of numbers for each location.

In [66]:
loc_stats=data.describe()
loc_stats

,RPT,VAL,ROS,KIL,SHA,BIR,DUB,CLA,MUL,CLO,BEL,MAL
count,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000,6546.000000
mean,12.359979,10.640267,11.656396,6.298587,10.448923,7.085066,9.793006,8.486601,8.490257,8.696705,13.110668,15.603129
std,5.618805,5.268695,5.007805,3.600942,4.933988,3.967735,4.978030,4.498299,4.165947,4.500488,5.829054,6.702178
min,0.670000,0.210000,1.500000,0.000000,0.130000,0.000000,0.000000,0.000000,0.000000,0.040000,0.130000,0.670000
25%,8.120000,6.670000,7.970000,3.580000,6.750000,4.000000,6.000000,5.090000,5.370000,5.330000,8.670000,10.710000
50%,11.710000,10.130000,10.920000,5.750000,9.960000,6.830000,9.210000,8.080000,8.170000,8.250000,12.500000,15.000000
75%,15.920000,14.040000,14.670000,8.380000,13.540000,9.670000,12.960000,11.420000,11.170000,11.580000,16.880000,19.860000
max,35.800000,33.370000,33.840000,28.460000,37.540000,26.160000,30.370000,31.080000,25.880000,28.210000,42.380000,42.540000

### Step 10. Create a DataFrame called day_stats and calculate the min, max and mean windspeed and standard deviations of the windspeeds across all the locations at each day.

#### A different set of numbers for each day.

In [67]:
minseries=pd.Series(data.min(axis=1),data.index)
maxseries=pd.Series(data.max(axis=1),data.index)
meanseries=pd.Series(data.mean(axis=1),data.index)
stdseries=pd.Series(data.std(axis=1),data.index)
day_stats=pd.DataFrame({"min":minseries,"max":maxseries,"mean":meanseries,"std":stdseries})
day_stats.head()

             min    max       mean       std
Date
1961-01-04  1.79  11.75   6.619167  3.198126
1961-01-05  6.17  13.33  10.630000  2.445356
1961-01-06  4.42  13.21   8.240000  2.998063
1961-01-07  4.96  14.29  10.385000  3.072114
1961-01-08  5.91  16.62  10.487500  3.547237

### Step 11. Find the average windspeed in January for each location.  
#### Treat January 1961 and January 1962 both as January.

In [73]:
data[data.index.month==1].mean()

RPT    14.831609
VAL    12.885389
ROS    13.276275
KIL     7.152477
SHA    11.644467
BIR     8.030561
DUB    11.788336
CLA     9.486962
MUL     9.511501
CLO    10.024069
BEL    14.527848
MAL    18.041826
dtype: float64

### Step 12. Downsample the record to a yearly frequency for each location.

In [74]:
data.groupby(data.index.year).count()

      RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
Date
1961  340  340  340  340  340  340  340  340  340  340  340  340
1962  362  362  362  362  362  362  362  362  362  362  362  362
1963  365  365  365  365  365  365  365  365  365  365  365  365
1964  366  366  366  366  366  366  366  366  366  366  366  366
1965  365  365  365  365  365  365  365  365  365  365  365  365
1966  365  365  365  365  365  365  365  365  365  365  365  365
1967  365  365  365  365  365  365  365  365  365  365  365  365
1968  366  366  366  366  366  366  366  366  366  366  366  366
1969  365  365  365  365  365  365  365  365  365  365  365  365
1970  365  365  365  365  365  365  365  365  365  365  365  365
1971  365  365  365  365  365  365  365  365  365  365  365  365
1972  366  366  366  366  366  366  366  366  366  366  366  366
1973  365  365  365  365  365  365  365  365  365  365  365  365
1974  365  365  365  365  365  365  365  365  365  365  365  365
1975  365  365  365  365  365  365  365  365  365  365  365  365
1976  366  366  366  366  366  366  366  366  366  366  366  366
1977  365  365  365  365  365  365  365  365  365  365  365  365
1978  365  365  365  365  365  365  365  365  365  365  365  365

### Step 13. Downsample the record to a monthly frequency for each location.

In [75]:
data.groupby(data.index.month).count()

      RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
Date
1     553  553  553  553  553  553  553  553  553  553  553  553
2     505  505  505  505  505  505  505  505  505  505  505  505
3     552  552  552  552  552  552  552  552  552  552  552  552
4     540  540  540  540  540  540  540  540  540  540  540  540
5     555  555  555  555  555  555  555  555  555  555  555  555
6     538  538  538  538  538  538  538  538  538  538  538  538
7     557  557  557  557  557  557  557  557  557  557  557  557
8     555  555  555  555  555  555  555  555  555  555  555  555
9     538  538  538  538  538  538  538  538  538  538  538  538
10    556  556  556  556  556  556  556  556  556  556  556  556
11    539  539  539  539  539  539  539  539  539  539  539  539
12    558  558  558  558  558  558  558  558  558  558  558  558

### Step 14. Downsample the record to a weekly frequency for each location.

In [117]:
#from datetime import datetime
#a = datetime.strptime("1965-1-1", "%Y-%m-%d")
#week = a.isocalendar()[1]
#week
#data[data.index.weekofyear==53]
data.groupby(data.index.weekofyear).count()

      RPT  VAL  ROS  KIL  SHA  BIR  DUB  CLA  MUL  CLO  BEL  MAL
Date
1     124  124  124  124  124  124  124  124  124  124  124  124
2     126  126  126  126  126  126  126  126  126  126  126  126
3     125  125  125  125  125  125  125  125  125  125  125  125
4     125  125  125  125  125  125  125  125  125  125  125  125
5     126  126  126  126  126  126  126  126  126  126  126  126
6     126  126  126  126  126  126  126  126  126  126  126  126
7     125  125  125  125  125  125  125  125  125  125  125  125
8     125  125  125  125  125  125  125  125  125  125  125  125
9     123  123  123  123  123  123  123  123  123  123  123  123
10    125  125  125  125  125  125  125  125  125  125  125  125
11    125  125  125  125  125  125  125  125  125  125  125  125
12    126  126  126  126  126  126  126  126  126  126  126  126
13    124  124  124  124  124  124  124  124  124  124  124  124
14    126  126  126  126  126  126  126  126  126  126  126  126
15    126  126  126  126  126  126  126  126  126  126  126  126
16    126  126  126  126  126  126  126  126  126  126  126  126
17    126  126  126  126  126  126  126  126  126  126  126  126
18    126  126  126  126  126  126  126  126  126  126  126  126
19    125  125  125  125  125  125  125  125  125  125  125  125
20    125  125  125  125  125  125  125  125  125  125  125  125
21    125  125  125  125  125  125  125  125  125  125  125  125
22    126  126  126  126  126  126  126  126  126  126  126  126
23    126  126  126  126  126  126  126  126  126  126  126  126
24    126  126  126  126  126  126  126  126  126  126  126  126
25    126  126  126  126  126  126  126  126  126  126  126  126
26    124  124  124  124  124  124  124  124  124  124  124  124
27    125  125  125  125  125  125  125  125  125  125  125  125
28    126  126  126  126  126  126  126  126  126  126  126  126
29    126  126  126  126  126  126  126  126  126  126  126  126
30    126  126  126  126  126  126  126  126  126  126  126  126
31    126  126  126  126  126  126  126  126  126  126  126  126
32    124  124  124  124  124  124  124  124  124  124  124  124
33    125  125  125  125  125  125  125  125  125  125  125  125
34    126  126  126  126  126  126  126  126  126  126  126  126
35    126  126  126  126  126  126  126  126  126  126  126  126
36    126  126  126  126  126  126  126  126  126  126  126  126
37    126  126  126  126  126  126  126  126  126  126  126  126
38    125  125  125  125  125  125  125  125  125  125  125  125
39    125  125  125  125  125  125  125  125  125  125  125  125
40    126  126  126  126  126  126  126  126  126  126  126  126
41    125  125  125  125  125  125  125  125  125  125  125  125
42    126  126  126  126  126  126  126  126  126  126  126  126
43    125  125  125  125  125  125  125  125  125  125  125  125
44    126  126  126  126  126  126  126  126  126  126  126  126
45    126  126  126  126  126  126  126  126  126  126  126  126
46    126  126  126  126  126  126  126  126  126  126  126  126
47    125  125  125  125  125  125  125  125  125  125  125  125
48    126  126  126  126  126  126  126  126  126  126  126  126
49    126  126  126  126  126  126  126  126  126  126  126  126
50    126  126  126  126  126  126  126  126  126  126  126  126
51    126  126  126  126  126  126  126  126  126  126  126  126
52    126  126  126  126  126  126  126  126  126  126  126  126
53     21   21   21   21   21   21   21   21   21   21   21   21

### Step 15. Calculate the min, max and mean windspeeds and standard deviations of the windspeeds across all locations for each week (assume that the first week starts on January 2 1961) for the first 52 weeks.

In [135]:
daterange=pd.date_range(start='1/2/1961', periods=52*7, freq='D')
newdata=data.loc[daterange,:]
newdata.groupby(newdata.index.week).describe()

     RPT                                                                VAL  \
   count       mean       std    min      25%     50%      75%    max count
1    5.0  12.316000  1.421418  10.58  10.9600  13.210  13.3300  13.50   5.0
2    7.0  12.468571  3.555392   9.04  10.2500  12.040  12.9750  19.75   7.0
3    6.0  12.100000  4.893064   4.92   9.5900  11.960  15.8975  17.75   6.0
4    6.0  19.880000  4.619061  13.62  16.8225  19.855  23.7875  25.04   6.0
5    7.0  16.827143  5.251408  10.58  13.2300  14.370  21.0850  24.21   7.0
6    7.0  19.684286  3.587677  16.00  17.1000  18.050  22.5000  24.54   7.0
7    6.0  14.956667  5.525210   6.04  12.8725  16.020  17.0075  22.50   6.0
8    7.0  15.221429  7.020716   7.79   9.8750  12.290  20.4600  25.80   7.0
9    5.0  11.824000  1.071742  10.96  11.0000  11.250  12.5800  13.33   5.0
10   6.0   9.376667  3.732263   4.88   6.7300   9.085  11.6275  14.79   6.0
11   7.0  11.911429  3.860036   4.92  11.1650  11.420  13.9150  16.88   7.0
12   7.0   9.567143  3.613298   6.29   6.3600   9.540  11.7100  15.00   7.0
13   5.0   9.818000  4.853908   5.88   7.6200   8.380   8.9600  18.25   5.0
14   7.0  11.964286  4.604392   4.50   9.2750  13.370  14.6050  18.12   7.0
15   7.0   8.965714  3.937727   4.71   5.4600  10.500  10.5650  15.50   7.0
16   7.0  12.621429  5.676655   4.00   9.5000  12.210  16.0250  21.09   7.0
17   7.0  10.117143  4.349662   4.08   7.5600   9.620  12.8550  16.29   7.0
18   7.0  15.367143  5.025507   9.87  10.8150  15.870  18.6000  23.00   7.0
19   6.0   7.901667  3.673850   3.54   5.1025   7.645  10.5625  12.79   6.0
20   6.0   8.561667  3.857369   4.88   5.4575   8.225   9.9050  15.04   6.0
21   6.0   7.550000  2.433828   4.96   5.7175   6.960   9.3875  10.92   6.0
22   7.0  10.321429  3.099701   7.00   8.0000  10.000  11.6650  15.92   7.0
23   7.0  10.917143  2.248597   8.29   9.0200  11.580  12.0450  14.42   7.0
24   7.0  10.571429  3.009482   6.13   8.7900   9.960  13.0000  14.33   7.0
25   7.0   7.345714  1.982035   4.00   6.0650   8.540   8.8750   9.00   7.0
26   5.0   9.826000  2.629340   7.21   7.7500   9.000  12.0400  13.13   5.0
27   6.0  11.806667  4.005984   7.29   8.8025  11.355  14.3800  17.50   6.0
28   7.0  16.680000  5.168710   8.63  13.9150  16.920  20.4400  22.50   7.0
29   7.0   4.202857  1.047978   3.04   3.3500   4.250   4.7750   5.88   7.0
30   7.0  10.561429  4.157641   6.13   7.1050  10.130  13.6900  16.08   7.0
31   7.0  10.870000  2.950887   7.67   8.9850  10.000  12.1850  16.08   7.0
32   5.0   9.928000  4.931346   2.88   6.6300  12.960  12.9600  14.21   5.0
33   6.0  15.471667  2.470590  13.13  13.6525  14.545  17.3950  18.91   6.0
34   7.0  12.391429  3.395857   7.67  10.4350  12.380  13.8300  18.16   7.0
35   7.0   8.678571  4.398615   3.63   5.2050   7.250  12.5000  14.46   7.0
36   7.0  10.541429  5.207278   5.00   6.2700   9.210  14.7100  17.62   7.0
37   7.0  17.160000  7.679190   5.33  13.2900  18.000  20.7300  28.75   7.0
38   6.0   8.291667  1.250191   6.92   7.3100   8.250   8.8750  10.25   6.0
39   6.0  14.850000  3.600911  10.34  12.0675  14.920  17.7425  19.12   6.0
40   7.0  11.250000  5.596710   3.13   7.0200  14.090  15.7050  16.08   7.0
41   6.0  10.881667  4.780675   3.71   8.4050  11.105  13.8350  17.12   6.0
42   7.0  19.260000  7.888314  10.46  12.6250  17.120  26.6850  28.62   7.0
43   6.0  14.353333  7.143390   4.33   8.9475  17.350  19.0400  21.34   6.0
44   7.0  11.571429  3.369201   5.88   9.5850  13.210  13.4750  15.79   7.0
45   7.0  10.428571  3.939811   5.46   7.8350   9.130  13.3300  16.08   7.0
46   7.0  10.798571  2.784358   7.50   8.6450  10.670  12.5650  15.00   7.0
47   6.0   9.638333  3.229622   5.75   7.0950   9.915  11.3325  14.29   6.0
48   7.0  12.608571  5.704669   7.92   8.7500   9.670  14.7100  23.75   7.0
49   7.0  17.362857  4.890152  10.83  14.2700  17.670  20.3950  23.71   7.0
50   7.0  14.985714  4.095106   9.29  12.2550  15.460  17.1500  21.34   7.0
51   7.0  15.757143  4.959717  11.46  12.2750  13.130  18.3750  24.41   7.0
52   7.0  13.634286  5.787783   5.04   9.5600  14.330  18.2050  20.54   7.0

               ...      BEL          MAL                                       \
         mean  ...      75%    max count       mean       std    min      25%
1   10.408000  ...  13.9600  16.62   5.0  13.226000  2.134978  10.88  11.8300
2    8.967143  ...  14.3150  20.71   7.0  11.024286  4.692355   5.17   6.8950
3    9.500000  ...  12.5000  15.92   6.0  10.346667  3.407132   6.79   8.1325
4   14.846667  ...  22.4425  26.08   6.0  22.388333  4.224639  17.50  18.7350
5   15.460000  ...  17.6900  19.33   7.0  11.935714  4.336104   7.17   8.4150
6   16.417143  ...  24.6000  26.38   7.0  19.155714  1.828705  17.04  17.6650
7   15.008333  ...  21.0850  28.62   6.0  15.925000  4.763632  10.96  11.8775
8   13.625714  ...  19.4350  23.21   7.0  14.322857  6.182283   6.67  10.6900
9   12.956000  ...  20.0000  23.45   5.0  14.108000  3.350772   8.83  13.7900
10  11.195000  ...  17.5700  22.71   6.0  13.066667  4.956336   5.54   9.9375
11  13.501429  ...  21.1250  22.79   7.0  16.227143  4.331958  11.34  12.7700
12   8.387143  ...  15.2900  21.34   7.0  18.134286  3.701846  13.13  15.1700
13   7.684000  ...  11.9600  18.63   5.0  12.910000  3.698547   7.17  12.2100
14  10.654286  ...  12.8750  17.16   7.0  11.371429  2.598271   7.21  10.2500
15   8.000000  ...  10.5850  16.17   7.0   8.690000  2.747842   5.66   6.5850
16  10.438571  ...  17.7950  19.21   7.0  12.470000  5.908542   4.96   8.9600
17   9.798571  ...  12.1900  13.04   7.0   8.637143  5.108365   2.67   5.4800
18  13.970000  ...  22.6300  28.08   7.0  14.571429  7.728504   3.83  11.6850
19   7.645000  ...  10.6525  18.66   6.0  10.530000  8.597707   3.33   4.4000
20   5.631667  ...  10.8100  12.00   6.0  10.256667  3.476795   5.91   8.2625
21   6.536667  ...  11.4575  13.88   6.0  10.883333  3.445685   8.00   8.4525
22   7.407143  ...  13.1500  17.00   7.0  13.597143  2.593586  10.63  11.7700
23   8.992857  ...  12.3350  16.17   7.0  12.250000  4.925055   5.96   8.5400
24   9.565714  ...  18.9800  25.25   7.0  15.025714  6.242673   6.13  11.5850
25   6.108571  ...  14.8350  19.08   7.0  17.410000  3.063011  13.75  15.0400
26   8.310000  ...  13.2900  19.92   5.0  12.402000  4.016574   8.50   8.7100
27   7.221667  ...  12.3025  20.41   6.0  15.750000  3.956322  12.08  12.5650
28  13.518571  ...  16.4200  20.25   7.0  12.524286  4.974273   5.96   9.9200
29   4.255714  ...   8.8950  10.13   7.0   8.415714  2.133994   5.41   7.1450
30   8.445714  ...  15.2750  22.17   7.0  13.761429  6.664574   6.13   9.2900
31   8.792857  ...  15.7250  18.54   7.0  13.760000  4.448251   9.08  10.2300
32   8.026000  ...  12.5000  14.00   5.0   9.858000  3.697340   5.88   6.8300
33  10.513333  ...  16.8425  21.92   6.0  16.626667  3.934238  13.04  14.8625
34  11.430000  ...  21.0850  23.38   7.0  16.485714  4.947608   8.29  13.9950
35   8.821429  ...  18.9550  24.71   7.0  11.022857  6.308087   5.41   7.0400
36   8.798571  ...  13.7700  15.83   7.0  11.034286  6.049619   3.37   6.3750
37  14.440000  ...  23.6800  23.91   7.0  18.984286  6.332885  14.67  16.2100
38   7.645000  ...  12.8050  20.96   6.0   9.915000  3.398163   5.25   7.6950
39  11.361667  ...  19.5650  20.30   6.0  12.701667  4.802201   4.04  11.1700
40   8.757143  ...  10.7950  17.83   7.0  11.410000  5.462002   4.83   7.4150
41   9.905000  ...  18.0050  20.46   6.0  16.011667  3.925249  11.96  12.8400
42  13.364286  ...  21.8950  24.71   7.0  23.641429  7.468377  13.46  19.1650
43  10.303333  ...  16.1100  22.29   6.0  16.325000  6.867864   9.83  12.1575
44   9.590000  ...  18.9200  20.17   7.0  19.195714  3.870800  13.37  16.8150
45   7.690000  ...  11.0600  12.58   7.0  10.858571  3.690752   5.71   8.1700
46   7.951429  ...   9.3950   9.59   7.0   5.737143  3.787654   2.00   3.1650
47   6.886667  ...  16.2050  20.46   6.0  14.146667  5.790840   8.71   9.1175
48  10.442857  ...  15.7500  19.04   7.0  14.725714  5.233192   5.88  12.3950
49  14.362857  ...  19.8550  21.79   7.0  16.241429  7.345893   7.58  11.3750
50  13.472857  ...  19.4800  22.83   7.0  14.644286  5.665006   6.50  11.1300
51  11.971429  ...  13.8750  17.67   7.0   8.164286  5.048035   2.62   4.7900
52   9.504286  ...  11.8750  13.21   7.0  12.840000  3.012729   6.63  12.4800


       50%      75%    max
1   13.170  13.7900  16.46
2   11.830  14.7300  16.92
3    9.480  11.7950  16.08
4   22.915  25.2500  27.63
5   11.710  14.2950  19.25
6   19.210  20.3350  21.84
7   15.460  19.1700  22.58
8   13.210  17.5650  23.87
9   14.000  16.3800  17.54
10  14.435  16.6525  18.16
11  15.710  19.0250  22.95
12  18.340  21.3150  22.50
13  13.000  15.3400  16.83
14  11.500  12.5250  15.34
15   7.710  10.7100  12.87
16  11.580  16.1850  20.46
17   8.460  10.4350  17.50
18  12.420  17.9000  26.58
19   8.670  12.0925  26.30
20   9.380  12.8600  14.96
21   9.795  11.9475  17.04
22  12.920  15.0650  17.96
23  12.290  15.2950  19.83
24  13.960  18.6050  24.71
25  16.880  19.8300  21.50
26  11.630  16.3800  16.79
27  14.520  18.7625  21.29
28  12.620  13.6450  21.96
29   8.330   9.9800  10.92
30  13.000  16.6250  25.37
31  11.870  17.3300  20.25
32  10.460  10.9600  15.16
33  15.835  16.1175  24.30
34  16.170  20.3300  22.29
35   8.000  13.5650  22.54
36  10.830  15.0200  20.25
37  16.750  17.9800  33.09
38  10.230  11.7900  14.62
39  15.000  15.8000  16.21
40   9.920  15.3350  19.62
41  15.415  19.0475  21.04
42  23.000  28.6250  33.45
43  13.020  22.0725  25.12
44  20.040  21.8750  23.58
45  11.460  13.4800  15.54
46   5.370   6.6050  13.25
47  13.150  17.9250  22.58
48  14.370  18.3750  21.29
49  15.410  19.3100  29.33
50  16.130  18.2500  21.12
51   5.910  11.2100  16.62
52  13.790  14.6450  15.21

[52 rows x 96 columns]